export const episodes = [
  {
    id: "1",
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "S01E01",
    characters: [
      {
        id: "1",
        name: "Rick Sanchez",
        image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
        __typename: "Character",
      },
      {
        id: "2",
        name: "Morty Smith",
        image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
        __typename: "Character",
      },
      {
        id: "35",
        name: "Bepisian",
        image: "https://rickandmortyapi.com/api/character/avatar/35.jpeg",
        __typename: "Character",
      },
      {
        id: "38",
        name: "Beth Smith",
        image: "https://rickandmortyapi.com/api/character/avatar/38.jpeg",
        __typename: "Character",
      },
      {
        id: "62",
        name: "Canklanker Thom",
        image: "https://rickandmortyapi.com/api/character/avatar/62.jpeg",
        __typename: "Character",
      },
      {
        id: "92",
        name: "Davin",
        image: "https://rickandmortyapi.com/api/character/avatar/92.jpeg",
        __typename: "Character",
      },
      {
        id: "127",
        name: "Frank Palicky",
        image: "https://rickandmortyapi.com/api/character/avatar/127.jpeg",
        __typename: "Character",
      },
      {
        id: "144",
        name: "Glenn",
        image: "https://rickandmortyapi.com/api/character/avatar/144.jpeg",
        __typename: "Character",
      },
      {
        id: "158",
        name: "Hookah Alien",
        image: "https://rickandmortyapi.com/api/character/avatar/158.jpeg",
        __typename: "Character",
      },
      {
        id: "175",
        name: "Jerry Smith",
        image: "https://rickandmortyapi.com/api/character/avatar/175.jpeg",
        __typename: "Character",
      },
      {
        id: "179",
        name: "Jessica",
        image: "https://rickandmortyapi.com/api/character/avatar/179.jpeg",
        __typename: "Character",
      },
      {
        id: "181",
        name: "Jessica's Friend",
        image: "https://rickandmortyapi.com/api/character/avatar/181.jpeg",
        __typename: "Character",
      },
      {
        id: "239",
        name: "Mr. Goldenfold",
        image: "https://rickandmortyapi.com/api/character/avatar/239.jpeg",
        __typename: "Character",
      },
      {
        id: "249",
        name: "Mrs. Sanchez",
        image: "https://rickandmortyapi.com/api/character/avatar/249.jpeg",
        __typename: "Character",
      },
      {
        id: "271",
        name: "Principal Vagina",
        image: "https://rickandmortyapi.com/api/character/avatar/271.jpeg",
        __typename: "Character",
      },
      {
        id: "338",
        name: "Summer Smith",
        image: "https://rickandmortyapi.com/api/character/avatar/338.jpeg",
        __typename: "Character",
      },
      {
        id: "394",
        name: "Davin",
        image: "https://rickandmortyapi.com/api/character/avatar/394.jpeg",
        __typename: "Character",
      },
      {
        id: "395",
        name: "Greebybobe",
        image: "https://rickandmortyapi.com/api/character/avatar/395.jpeg",
        __typename: "Character",
      },
      {
        id: "435",
        name: "Pripudlian",
        image: "https://rickandmortyapi.com/api/character/avatar/435.jpeg",
        __typename: "Character",
      },
    ],
    created: "2017-11-10T12:56:33.798Z",
  },
]

export const characters = [
  {
    id: "1",
    name: "Rick Sanchez",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: "1",
      name: "Earth (C-137)",
      type: "Planet",
      dimension: "Dimension C-137",
      __typename: "Location",
    },
    location: {
      id: "3",
      name: "Citadel of Ricks",
      type: "Space station",
      dimension: "unknown",
      __typename: "Location",
    },
    image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
    episode: [
      {
        id: "1",
        name: "Pilot",
        air_date: "December 2, 2013",
        __typename: "Episode",
      },
      {
        id: "2",
        name: "Lawnmower Dog",
        air_date: "December 9, 2013",
        __typename: "Episode",
      },
      {
        id: "3",
        name: "Anatomy Park",
        air_date: "December 16, 2013",
        __typename: "Episode",
      },
      {
        id: "4",
        name: "M. Night Shaym-Aliens!",
        air_date: "January 13, 2014",
        __typename: "Episode",
      },
      {
        id: "5",
        name: "Meeseeks and Destroy",
        air_date: "January 20, 2014",
        __typename: "Episode",
      },
      {
        id: "6",
        name: "Rick Potion #9",
        air_date: "January 27, 2014",
        __typename: "Episode",
      },
      {
        id: "7",
        name: "Raising Gazorpazorp",
        air_date: "March 10, 2014",
        __typename: "Episode",
      },
      {
        id: "8",
        name: "Rixty Minutes",
        air_date: "March 17, 2014",
        __typename: "Episode",
      },
      {
        id: "9",
        name: "Something Ricked This Way Comes",
        air_date: "March 24, 2014",
        __typename: "Episode",
      },
      {
        id: "10",
        name: "Close Rick-counters of the Rick Kind",
        air_date: "April 7, 2014",
        __typename: "Episode",
      },
      {
        id: "11",
        name: "Ricksy Business",
        air_date: "April 14, 2014",
        __typename: "Episode",
      },
      {
        id: "12",
        name: "A Rickle in Time",
        air_date: "July 26, 2015",
        __typename: "Episode",
      },
      {
        id: "13",
        name: "Mortynight Run",
        air_date: "August 2, 2015",
        __typename: "Episode",
      },
      {
        id: "14",
        name: "Auto Erotic Assimilation",
        air_date: "August 9, 2015",
        __typename: "Episode",
      },
      {
        id: "15",
        name: "Total Rickall",
        air_date: "August 16, 2015",
        __typename: "Episode",
      },
      {
        id: "16",
        name: "Get Schwifty",
        air_date: "August 23, 2015",
        __typename: "Episode",
      },
      {
        id: "17",
        name: "The Ricks Must Be Crazy",
        air_date: "August 30, 2015",
        __typename: "Episode",
      },
      {
        id: "18",
        name: "Big Trouble in Little Sanchez",
        air_date: "September 13, 2015",
        __typename: "Episode",
      },
      {
        id: "19",
        name: "Interdimensional Cable 2: Tempting Fate",
        air_date: "September 20, 2015",
        __typename: "Episode",
      },
      {
        id: "20",
        name: "Look Who's Purging Now",
        air_date: "September 27, 2015",
        __typename: "Episode",
      },
      {
        id: "21",
        name: "The Wedding Squanchers",
        air_date: "October 4, 2015",
        __typename: "Episode",
      },
      {
        id: "22",
        name: "The Rickshank Rickdemption",
        air_date: "April 1, 2017",
        __typename: "Episode",
      },
      {
        id: "23",
        name: "Rickmancing the Stone",
        air_date: "July 30, 2017",
        __typename: "Episode",
      },
      {
        id: "24",
        name: "Pickle Rick",
        air_date: "August 6, 2017",
        __typename: "Episode",
      },
      {
        id: "25",
        name: "Vindicators 3: The Return of Worldender",
        air_date: "August 13, 2017",
        __typename: "Episode",
      },
      {
        id: "26",
        name: "The Whirly Dirly Conspiracy",
        air_date: "August 20, 2017",
        __typename: "Episode",
      },
      {
        id: "27",
        name: "Rest and Ricklaxation",
        air_date: "August 27, 2017",
        __typename: "Episode",
      },
      {
        id: "28",
        name: "The Ricklantis Mixup",
        air_date: "September 10, 2017",
        __typename: "Episode",
      },
      {
        id: "29",
        name: "Morty's Mind Blowers",
        air_date: "September 17, 2017",
        __typename: "Episode",
      },
      {
        id: "30",
        name: "The ABC's of Beth",
        air_date: "September 24, 2017",
        __typename: "Episode",
      },
      {
        id: "31",
        name: "The Rickchurian Mortydate",
        air_date: "October 1, 2017",
        __typename: "Episode",
      },
      {
        id: "32",
        name: "Edge of Tomorty: Rick, Die, Rickpeat",
        air_date: "November 10, 2019",
        __typename: "Episode",
      },
      {
        id: "33",
        name: "The Old Man and the Seat",
        air_date: "November 17, 2019",
        __typename: "Episode",
      },
      {
        id: "34",
        name: "One Crew Over the Crewcoo's Morty",
        air_date: "November 24, 2019",
        __typename: "Episode",
      },
      {
        id: "35",
        name: "Claw and Hoarder: Special Ricktim's Morty",
        air_date: "December 8, 2019",
        __typename: "Episode",
      },
      {
        id: "36",
        name: "Rattlestar Ricklactica",
        air_date: "December 15, 2019",
        __typename: "Episode",
      },
      {
        id: "37",
        name: "Never Ricking Morty",
        air_date: "May 3, 2020",
        __typename: "Episode",
      },
      {
        id: "38",
        name: "Promortyus",
        air_date: "May 10, 2020",
        __typename: "Episode",
      },
      {
        id: "39",
        name: "The Vat of Acid Episode",
        air_date: "May 17, 2020",
        __typename: "Episode",
      },
      {
        id: "40",
        name: "Childrick of Mort",
        air_date: "May 24, 2020",
        __typename: "Episode",
      },
      {
        id: "41",
        name: "Star Mort: Rickturn of the Jerri",
        air_date: "May 31, 2020",
        __typename: "Episode",
      },
      {
        id: "42",
        name: "Mort Dinner Rick Andre",
        air_date: "June 20, 2021",
        __typename: "Episode",
      },
      {
        id: "43",
        name: "Mortyplicity",
        air_date: "June 27, 2021",
        __typename: "Episode",
      },
      {
        id: "44",
        name: "A Rickconvenient Mort",
        air_date: "July 4, 2021",
        __typename: "Episode",
      },
      {
        id: "45",
        name: "Rickdependence Spray",
        air_date: "July 11, 2021",
        __typename: "Episode",
      },
      {
        id: "46",
        name: "Amortycan Grickfitti",
        air_date: "July 18, 2021",
        __typename: "Episode",
      },
      {
        id: "47",
        name: "Rick & Morty's Thanksploitation Spectacular",
        air_date: "July 25, 2021",
        __typename: "Episode",
      },
      {
        id: "48",
        name: "Gotron Jerrysis Rickvangelion",
        air_date: "August 1, 2021",
        __typename: "Episode",
      },
      {
        id: "49",
        name: "Rickternal Friendshine of the Spotless Mort",
        air_date: "August 8, 2021",
        __typename: "Episode",
      },
      {
        id: "50",
        name: "Forgetting Sarick Mortshall",
        air_date: "September 5, 2021",
        __typename: "Episode",
      },
      {
        id: "51",
        name: "Rickmurai Jack",
        air_date: "September 5, 2021",
        __typename: "Episode",
      },
    ],
    created: "2017-11-04T18:48:46.250Z",
  },
]

export const locations = [
  {
    id: "1",
    name: "Earth (C-137)",
    type: "Planet",
    dimension: "Dimension C-137",
    residents: [
      {
        id: "38",
        name: "Beth Smith",
        image: "https://rickandmortyapi.com/api/character/avatar/38.jpeg",
        __typename: "Character",
      },
      {
        id: "45",
        name: "Bill",
        image: "https://rickandmortyapi.com/api/character/avatar/45.jpeg",
        __typename: "Character",
      },
      {
        id: "71",
        name: "Conroy",
        image: "https://rickandmortyapi.com/api/character/avatar/71.jpeg",
        __typename: "Character",
      },
      {
        id: "82",
        name: "Cronenberg Rick",
        image: "https://rickandmortyapi.com/api/character/avatar/82.jpeg",
        __typename: "Character",
      },
      {
        id: "83",
        name: "Cronenberg Morty",
        image: "https://rickandmortyapi.com/api/character/avatar/83.jpeg",
        __typename: "Character",
      },
      {
        id: "92",
        name: "Davin",
        image: "https://rickandmortyapi.com/api/character/avatar/92.jpeg",
        __typename: "Character",
      },
      {
        id: "112",
        name: "Eric McMan",
        image: "https://rickandmortyapi.com/api/character/avatar/112.jpeg",
        __typename: "Character",
      },
      {
        id: "114",
        name: "Ethan",
        image: "https://rickandmortyapi.com/api/character/avatar/114.jpeg",
        __typename: "Character",
      },
      {
        id: "116",
        name: "Evil Beth Clone",
        image: "https://rickandmortyapi.com/api/character/avatar/116.jpeg",
        __typename: "Character",
      },
      {
        id: "117",
        name: "Evil Jerry Clone",
        image: "https://rickandmortyapi.com/api/character/avatar/117.jpeg",
        __typename: "Character",
      },
      {
        id: "120",
        name: "Evil Summer Clone",
        image: "https://rickandmortyapi.com/api/character/avatar/120.jpeg",
        __typename: "Character",
      },
      {
        id: "127",
        name: "Frank Palicky",
        image: "https://rickandmortyapi.com/api/character/avatar/127.jpeg",
        __typename: "Character",
      },
      {
        id: "155",
        name: "Harold",
        image: "https://rickandmortyapi.com/api/character/avatar/155.jpeg",
        __typename: "Character",
      },
      {
        id: "169",
        name: "Jacob",
        image: "https://rickandmortyapi.com/api/character/avatar/169.jpeg",
        __typename: "Character",
      },
      {
        id: "175",
        name: "Jerry Smith",
        image: "https://rickandmortyapi.com/api/character/avatar/175.jpeg",
        __typename: "Character",
      },
      {
        id: "179",
        name: "Jessica",
        image: "https://rickandmortyapi.com/api/character/avatar/179.jpeg",
        __typename: "Character",
      },
      {
        id: "186",
        name: "Joyce Smith",
        image: "https://rickandmortyapi.com/api/character/avatar/186.jpeg",
        __typename: "Character",
      },
      {
        id: "201",
        name: "Leonard Smith",
        image: "https://rickandmortyapi.com/api/character/avatar/201.jpeg",
        __typename: "Character",
      },
      {
        id: "216",
        name: "MC Haps",
        image: "https://rickandmortyapi.com/api/character/avatar/216.jpeg",
        __typename: "Character",
      },
      {
        id: "239",
        name: "Mr. Goldenfold",
        image: "https://rickandmortyapi.com/api/character/avatar/239.jpeg",
        __typename: "Character",
      },
      {
        id: "271",
        name: "Principal Vagina",
        image: "https://rickandmortyapi.com/api/character/avatar/271.jpeg",
        __typename: "Character",
      },
      {
        id: "302",
        name: "Ruben",
        image: "https://rickandmortyapi.com/api/character/avatar/302.jpeg",
        __typename: "Character",
      },
      {
        id: "303",
        name: "Samantha",
        image: "https://rickandmortyapi.com/api/character/avatar/303.jpeg",
        __typename: "Character",
      },
      {
        id: "338",
        name: "Summer Smith",
        image: "https://rickandmortyapi.com/api/character/avatar/338.jpeg",
        __typename: "Character",
      },
      {
        id: "343",
        name: "Tammy Guetermann",
        image: "https://rickandmortyapi.com/api/character/avatar/343.jpeg",
        __typename: "Character",
      },
      {
        id: "356",
        name: "Tom Randolph",
        image: "https://rickandmortyapi.com/api/character/avatar/356.jpeg",
        __typename: "Character",
      },
      {
        id: "394",
        name: "Davin",
        image: "https://rickandmortyapi.com/api/character/avatar/394.jpeg",
        __typename: "Character",
      },
    ],
    created: "2017-11-10T12:42:04.162Z",
  },
]
